[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "imagekitio>=5.9.0",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.3",
]

[project.scripts]
project = "project:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
